// <auto-generated />
using Blazor.FacileBudget.DataAccess.Models.Services.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.FacileBudget.DataAccess.Migrations
{
    [DbContext(typeof(FacileBudgetDbContext))]
    partial class FacileBudgetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Blazor.FacileBudget.DataAccess.Models.Entities.Spesa", b =>
                {
                    b.Property<int>("SpesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mese")
                        .HasColumnType("TEXT");

                    b.HasKey("SpesaId");

                    b.ToTable("Spese");
                });

            modelBuilder.Entity("Blazor.FacileBudget.DataAccess.Models.Entities.Spesa", b =>
                {
                    b.OwnsOne("Blazor.FacileBudget.Models.ValueObjects.Money", "Importo", b1 =>
                        {
                            b1.Property<int>("SpesaId")
                                .HasColumnType("INTEGER");

                            b1.Property<float>("Amount")
                                .HasColumnType("REAL")
                                .HasColumnName("Importo_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Importo_Currency");

                            b1.HasKey("SpesaId");

                            b1.ToTable("Spese");

                            b1.WithOwner()
                                .HasForeignKey("SpesaId");
                        });

                    b.Navigation("Importo");
                });
#pragma warning restore 612, 618
        }
    }
}
