name: GitHub build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/Blazor.FacileBudget.sln

    - name: Build
      run: dotnet build --no-restore src/Blazor.FacileBudget.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal src/Blazor.FacileBudget.sln
